version: "3.9"
services:
  frontend:
    build: 
      context: ./
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/src/contracts
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    stdin_open: true
    tty: true
    
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - ./backend:/app
    stdin_open: true
    tty: true